[package]
name = "chenzt23-tg-rcore-tutorial-syscall-t3l2"
description = "System call definitions and interfaces for rCore tutorial OS."
version = "0.0.1-preview.1"
edition = "2024"
authors = ["Zitao Chen <chen-zt23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/MuZhao2333/tg-rcore-tutorial/"
homepage = "https://github.com/MuZhao2333/tg-rcore-tutorial/tree/t3l2/tg-rcore-tutorial-syscall"
documentation = "https://docs.rs/tg-rcore-tutorial-syscall"
license = "GPL-3.0"
readme = "README.md"
keywords = ["rcore", "syscall", "no-std", "riscv"]
categories = ["no-std", "embedded"]

[dependencies]
spin = "0.9"
bitflags = "1.2"
tg-signal-defs = { package = "tg-rcore-tutorial-signal-defs", path = "../tg-rcore-tutorial-signal-defs", version = "0.4.8" }

[features]
kernel = []
user = []

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]
