[package]
name = "chenzt23-tg-rcore-tutorial-sync"
description = "Synchronization primitives for rCore tutorial OS, including mutex, semaphore, and condvar."
version = "0.0.1-preview.1"
edition = "2024"
aauthors = ["Zitao Chen <chen-zt23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/MuZhao2333/tg-rcore-tutorial/"
homepage = "https://github.com/MuZhao2333/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-sync"
documentation = "https://docs.rs/tg-rcore-tutorial-sync"
license = "GPL-3.0"
readme = "README.md"
keywords = ["rcore", "sync", "mutex", "riscv"]
categories = ["no-std", "embedded", "concurrency"]

[dependencies]
riscv = "0.10"
spin = "0.9"
tg-task-manage = { package = "tg-rcore-tutorial-task-manage", path = "../tg-rcore-tutorial-task-manage", version = "0.4.8" }
